### PR TITLE
Masked cohort logo samples (vector)

### PR DESCRIPTION
**Pull request by Preciousutos**
Merging pull request to #15 
Vector samples of Masked cohort logo

### CODE REVIEW

**Comment by yochannah** [comment]
@Preciousutos wow, these samples are truly gorgeous! I especially like the eyebrow-over-mask one 😁 

In terms of the visuals, I have no suggestions for changes. In terms of the files - the jpg is great, but what would also be handy would be: 

1. the vector original design files in whatever format you have (.ai. .psd, other?) with clearly named layers (not layer-2 and layer 3-copy). 
2. exports of each file individually with transparent backgrounds and clear names, in png format.

**Comment by Preciousutos** [comment]
I actually designed those using Figma but I can share the the svg file and the png for each of the designs.

**Comment by yochannah** [comment]
svg is perfect - it's an open format that doesn't require any special software, so arguably much better than any other option!

**Comment by Preciousutos** [comment]
Alright. Great

**Comment by Preciousutos** [comment]
Sample 1 (dark)
Sample 1 (light)
Sample 1 horz (dark)
Sample 1 horz (light)
Sample 1 ver (dark)
Sample 1 ver (light)
Sample 2 (dark)
Sample 2 (light)
Sample 2 horz (dark)
Sample 2 horz (light)
Sample 2 ver (dark)
Sample 2 ver (light)
Sample 3 (dark)
Sample 3 (light)
Sample 3 horz (dark)
Sample 3 horz (light)
Sample 3 ver (dark)
Sample 3 ver (light)
@yochannah these are the png files. I'm having a hard time sending the SVG files, should I create another pull request for that?

**Comment by NPDebs** [comment]
Precious, you are a star! 🌟
These cannot be merged too, for the same reason. Thank you for all the meaningful work.

All the best! ❤️

**Pull request closed without merging**
