### PR TITLE
Github Social Preview Samples

### PR DESCRIPTION
**Pull request by Preciousutos**
A few samples of suggested social previews for github.

### CODE REVIEW

**Comment by Ismael-KG** [comment]
just linking to #14

**Comment by Bisola15** [comment]
Hi @Preciousutos These are really nice 😊 and you came up with 5 samples!! This expresses your fluidity in design. Personally, I like the last two. I like the simplicity of it, one of the things a social preview should possess. Great work babes 💃🏾

**Comment by Preciousutos** [comment]
Thank you @Bisola15

**Comment by NPDebs** [comment]
Precious, thank you for the work here!
These cannot be merged, because we have a working design system now. However, you did meaningful work here.
Well done! ❤️

**Pull request closed without merging**
