### PR TITLE
Prints and digital folder

### PR DESCRIPTION
**Pull request by jilaga**
This folder will contain the following assets: 

- [x] Stickers
- [x] Business Cards
- [x] Flyers
- [x] Social Media Assets
- [x] letterheads

### CODE REVIEW

**Review by yochannah — CHANGES_REQUESTED** [review]
Hey Jilaga, I woke up last night remembering I'd forgotten to review this 😅  

This is great! One request before merging: Can you please make copies of each logo in an editable format, too? Ideally SVG with text as curves AND SVG with text as text. Once that's done, I'll be happy to merge it!

**Comment by yochannah** [comment]
p.s. my favourite is prints-and-digital/stickers/watering-seedling -transparent-bg.png - SO PRETTY AND CUTE

**Comment by jilaga** [comment]
I had a mini internal conflict about uploading the editable files because I used a lot of layer manipulation to achieve the stickers so editing might not be so straightforward. 🤔

> we have the same favorite 😉

**Review by yochannah — APPROVED** [review]

**Comment by yochannah** [comment]
> I had a mini internal conflict about uploading the editable files because I used a lot of layer manipulation to achieve the stickers so editing might not be so straightforward

That makes sense! Well-labelled layers can help with this - there's nothing more lovely than opening a .psd (or choose your preferred non-propretary option) and seeing layers that are groups and named sensible things like "Background shading" rather than Layer 12 (copy) 😂

**Pull request merged**
