### PR TITLE
Social preview Images

### PR DESCRIPTION
**Pull request by Bisola15**
GitHub Social Preview Task... Light mode and darkmode. For this I had done some research after taking a look at the image. Found out what social preview meant and how they are represented on other social platforms. This results are what I have here.

### CODE REVIEW

**Review by jilaga — CHANGES_REQUESTED** [review]
hi @Bisola15 This is a really good concept for the social preview. 
what do you think about having *+7 more* and *contributors* on the same line with the same properties cos I think its one sentence? and also increasing the margins of the frame?

**Comment by Bisola15** [comment]
> hi @Bisola15 This is a really good concept for the social preview. what do you think about having _+7 more_ and _contributors_ on the same line with the same properties cos I think its one sentence? and also increasing the margins of the frame?

Thank you Jilaga. The 'contributors' is actually a label and not a sentence with the number. And the spacing Yeah??... So I played around with the spacing a lot before settling for this. I was a bit conflicted on it tbh and after doing the research I did see a pattern in the less space management. I'll do a version with more spacing and share. 

Thank you so much!

**Comment by jilaga** [comment]
> > hi @Bisola15 This is a really good concept for the social preview. what do you think about having _+7 more_ and _contributors_ on the same line with the same properties cos I think its one sentence? and also increasing the margins of the frame?
> 
> Thank you Jilaga. The 'contributors' is actually a label and not a sentence with the number. And the spacing Yeah??... So I played around with the spacing a lot before settling for this. I was a bit conflicted on it tbh and after doing the research I did see a pattern in the less space management. I'll do a version with more spacing and share.
> 
> Thank you so much!

>alright. cannot wait to see what it looks like!

**Comment by Ismael-KG** [comment]
Just linking this PR to issue #14

**Comment by Bisola15** [comment]
> Just linking this PR to issue #14

Hehehehehe 
Thank you 😊

**Comment by yochannah** [comment]
@Bisola15 I like the thought that has gone into this - maybe less text content, and instead focus a little more on visuals? It feels a little marketing-ey / sales-ey, I guess. Also, things like the people/numbers won't update automatically, so something that won't be easily out of date might be nice!

**Comment by Bisola15** [comment]
@yochannah Thank you for the review!! I'll look into that and make an update

**Comment by Bisola15** [comment]
Hi @yochannah, taking into consideration your thoughtful comment and correction, I came up with this visual.
OLS Social preview change

A review will be highly appreciated. @Ismael-KG 🤲🏾

**Comment by NPDebs** [comment]
Thank you all (creator and reviewers) for your work here! 🙌 

The contributions made in this PR are invaluable. 🌟 These will not be merged, as we have made significant progress with rebranding OLS. Regardless, your efforts are truly appreciated. Best of luck in all you do! ❤️

**Pull request closed without merging**
