### PR TITLE
Open seeds cohort logo proposals

### PR DESCRIPTION
**Pull request by stormztee**
openseeds3
openseeds4
openseeds1
openseeds2

### CODE REVIEW

**Comment by stormztee** [comment]
openseedssketch4
openseedssketch1
openseedssketch3

**Comment by Ismael-KG** [comment]
Just linking this to #24 😊

**Comment by stormztee** [comment]
> 

Thank you @Ismael-KG

**Comment by MargaretPearl** [comment]
Thank you @Ismael-KG for referencing Issue [24](https://github.com/open-life-science/branding/issues/24). The final open seeds design is attached below
Untitled-1

**Pull request closed without merging**
