### PR TITLE
Social Preview  Image For Github

### PR DESCRIPTION
**Pull request by Ososeomo**
I took a creative route while designing because I wanted to also give a bit of an insight on what the brand is about. I wasn't careful with the use of  the brands color, I made two designs almost  similar but unique. I'm very open to corrections or feedbacks if needed.

### CODE REVIEW

**Comment by Bisola15** [comment]
Hi Ososeomo, well done on the design! I like the concept of dark and light mode and I'm a dark mode person so I might be bias with the dark mode 😅,  The thinking process that went into this.
I noticed there is a grey square boundary surrounding the designs, is that intentional ?

And generally, I'm leaning towards the concept of the dark mode more... now now not because it is dark-mode as I have said. lol. The straightforwardness more like it for me.  

Also, what do you think about moving the contributors from bottom middle, to left so it aligns with the title and it is under it rather than far away from it for easy scanning by users?

**Comment by Ismael-KG** [comment]
Just linking this PR to issue #14

**Comment by Ososeomo** [comment]
> Hi Ososeomo, well done on the design! I like the concept of dark and light mode and I'm a dark mode person so I might be bias with the dark mode 😅, The thinking process that went into this. I noticed there is a grey square boundary surrounding the designs, is that intentional ?
> 
> And generally, I'm leaning towards the concept of the dark mode more... now now not because it is dark-mode as I have said. lol. The straightforwardness more like it for me.
> 
> Also, what do you think about moving the contributors from bottom middle, to left so it aligns with the title and it is under it rather than far away from it for easy scanning by users?

Thank you @Bisola15 for your suggestion, concerning the last suggestion, I was trying to avoid issues with colors over powering one another that's why I make it stand on its own and not in front of colorful vectors.

**Comment by ZeedDeveloper** [comment]
@Ososeomo well done, where do I go/click  to view your contribution please

**Comment by NPDebs** [comment]
Hi, Osose! 🌷
Your efforts here are appreciated! 🙏
These cannot be merged, because we have a working design system now. However, this is far from being a waste of time, as your skills really shined through. 🌟All the best! ❤️

**Pull request closed without merging**
