### PR TITLE
Added a Kenaz Logo

### PR DESCRIPTION
**Pull request by niyolynate**
Was to make a logo for kenaz hopefully i did.

### CODE REVIEW

**Comment by niyolynate** [comment]
Added a github social preview for OLS

**Comment by niyolynate** [comment]
Added a cohort open seed cohort logo
perseverance

**Comment by niyolynate** [comment]
Added illustration
[OLS illustration for core concept.pptx](https://github.com/open-life-science/branding/files/9920681/OLS.illustration.for.core.concept.pptx)
 of a presentation of slides showing the core Concept of OLS.

**Comment by NPDebs** [comment]
Thank you, niyolynate for your contribution! 🙏 
This PR will not be merged, since OLS has an established brand design now.

Please, continue your valuable contributions to open source and other projects. 🚀

**Pull request closed without merging**
