### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by iremide1022**
social preview (1)

a social preview design for github

### CODE REVIEW

**Comment by oneboyfromife** [comment]
Great work @iremide1022, we can work on the alignment to the left or what do you feel?

**Comment by Bisola15** [comment]
Hi Iremide, Such nice clean work.  Like oneboyfromife said, we can work more on the alignment and we can do more with spacing too for the users, contributors - part. Lemme know if you need any help. Xoxo

**Comment by Ismael-KG** [comment]
Just linking this PR to issue #14

**Comment by NPDebs** [comment]
Iremide, for the contributions you made, we'd like to thank you. 🌹
We appreciate your active participation. Although this won't be merged, because OLS has a unique brand identity, we do recognise the effort you put into creating PRs. 

All the best! ❤️

**Pull request closed without merging**
