### PR TITLE
added more logos

### PR DESCRIPTION
**Pull request by Emidowojo**
Pushed the logos again as I didn't see them merged

### CODE REVIEW

**Comment by Bisola15** [comment]
Hi Emidowojo.. Nice works you have there:

Love the simplicity of the first logo
The cartoon-ey style of the second logo makes me nostalgic.. it definitely made me miss being in the science field.
The third one gives the technology side of OLS vibe.. Lovely!
The last one just like the second, made me nostalgic. Well done!

I should say though, I don’t think there is a task that requires us to make a new logo for Open Life Science. I know there are some for cohorts logo and a discussion for renaming OLS.. I will check again to be sure though. 

Again... Well done!

**Comment by yochannah** [comment]
Oh.... WOW! Not much else to add except that these blow me away 🙏 They're not something we can use as official logos, but they're _so_ beautiful they definitely count as a contribution and proof that you're good at design. It's great you included the svg as well as the png!

**Review by yochannah — APPROVED** [review]

**Comment by Emidowojo** [comment]
Thank you so much @yochannah

**Comment by NPDebs** [comment]
Hi, Emidowojo. 👋
Thank you for putting so much effort into this PR! ❤️As much as we won't be merging these, as we have official logos now, your skills are evident. Please, keep creating magic. Best of luck!

**Pull request closed without merging**
