### PR TITLE
Openseeds logo

### PR DESCRIPTION
**Pull request by jilaga**

### CODE REVIEW

**Comment by bebatut** [comment]
I think your PR got mixed here with your other PR. This PR adds also the OLS logo

**Comment by jilaga** [comment]
I think its because i created a patch from my branch with OLS logo. Can i resolve this by creating another branch directly from Branding:master? (should i also continue creating a new branch for each pr?)

**Comment by bebatut** [comment]
Yes. For each new feature or Pull Request, the best is to create a new branch from the main/master branch.

**Comment by jilaga** [comment]
Thank you!

**Pull request closed without merging**
