### PR TITLE
3 pillars icons

### PR DESCRIPTION
**Pull request by jilaga**

### CODE REVIEW

**Review by NPDebs — APPROVED** [review]
Thanks for the PR, @jilaga! Looks good to me.

 Also, very smart of you to add both `.png` and `.svg` formats. ❤️

**Comment by bebatut** [comment]
Thanks @jilaga. Maybe better to move that outside the `print-and-digital` folder, so it is easier to find

**Comment by jilaga** [comment]
> Thanks @jilaga. Maybe better to move that outside the `print-and-digital` folder, so it is easier to find

That would be a lot better.

**Comment by bebatut** [comment]
Thanks a lot :)

**Pull request merged**
