### PR TITLE
Social preview images for Github

### PR DESCRIPTION
**Pull request by manuuelab**
I designed 2 versions to give you the chance to pick between the 2 options. I did not go for any dark theme in these designs because I did not see any dark colour scheme in the branding repo we are to take images from. Looking forward to hearing your thoughts on these

### CODE REVIEW

**Comment by Bisola15** [comment]
Hi Manuuelab, these designs are sleek tbh was legit staring at the screen for a while. Loved what you did with the X design on the first one. Well done!

If I had to choose though, I'd go with the second, I like the simplicity of it.
Oh and what do you think about increasing the size of the OLS logo on the design, if I didn’t already know that it was the OLS logo, I would have thought it was a part of the design?

**Comment by manuuelab** [comment]
> Hi Manuuelab, these designs are sleek tbh was legit staring at the screen for a while. Loved what you did with the X design on the first one. Well done!
> 
> If I had to choose though, I'd go with the second, I like the simplicity of it. Oh and what do you think about increasing the size of the OLS logo on the design, if I didn’t already know that it was the OLS logo, I would have thought it was a part of the design?

Hey Bisola, I appreciate your feedback and I'm glad you love the designs. Looking at the first design again, I do believe the logo needs some increment, but when I tried increasing the size more than what it is now, I did not like the contrast and it did look too bulky. I think a better option would be to increase the weight of the strokes in the logo, but that is beyond my power.

**Comment by Bisola15** [comment]
> > Hi Manuuelab, these designs are sleek tbh was legit staring at the screen for a while. Loved what you did with the X design on the first one. Well done!
> > If I had to choose though, I'd go with the second, I like the simplicity of it. Oh and what do you think about increasing the size of the OLS logo on the design, if I didn’t already know that it was the OLS logo, I would have thought it was a part of the design?
> 
> Hey Bisola, I appreciate your feedback and I'm glad you love the designs. Looking at the first design again, I do believe the logo needs some increment, but when I tried increasing the size more than what it is now, I did not like the contrast and it did look too bulky. I think a better option would be to increase the weight of the strokes in the logo, but that is beyond my power.

Where did you get the logo from? Is it an svg or png?
Let's see how we can work around it

**Comment by Ismael-KG** [comment]
Just linking this PR to issue #14

**Comment by NPDebs** [comment]
Thank you both for the work done here! 💪 

Manuel, this PR won't be merged, since we have a working design system now. However, please know that your skills and creativity did not go unnoticed. Thanks for your enthusiasm, and good luck!! ❤️

**Pull request closed without merging**
