### PR TITLE
CREATE  A NEW SOCIAL MEDIA PREVIEW FOR GITHUB

### PR DESCRIPTION
**Pull request by kosonyemedaniella**
I created two different designs for you to pick from . the two designs has its information centered in the middle to give the users full insight about what the github link is for . i am open to corrections and reviews as i am new to open source .

### CODE REVIEW

**Comment by Bisola15** [comment]
These are simple straightforward and neat!. Personal preference here, I'd say I like the second one more. It follows the brand style and colours. Since there isn’t a yellow in the OLS brand, that might not work much, what do you feel?

**Comment by kosonyemedaniella** [comment]
Hi bisola, thank you . I was actually testing the waters in the first one and truly yellow doesn’t resonate with the brand . As for the second one , I really love minimalist designs . Straight to the point without too much information

**Comment by Ismael-KG** [comment]
Just linking this PR to issue #14

**Comment by latifatakin** [comment]
@kosonyemedaniella your designs look neat and straightforward. Like @Bisola15 suggested, color yellow might not be in tone with the brand identity. I think that can be rectified. Overall, I like your designs!

**Comment by NPDebs** [comment]
Thank you for your efforts on the PR, Daniella. ❤️💪
Although these won't be merged, because we have a working design system now, your skills didn't go unnoticed. 

Best wishes. To infinity and beyond! 🚀

**Pull request closed without merging**
