### PR TITLE
Social preview image

### PR DESCRIPTION
**Pull request by jilaga**
#4 The designs are quite distinct from each other. 2 are more of the OLS brand image and the other is just me trying to risk a different approach. I would like feedback on the most preferred and I can share the svgs for changes to be made because I'm still figuring open source out, thanks.

### CODE REVIEW

**Comment by jilaga** [comment]
Who thinks this is a better approach to the last design? 
OLS social cover1

**Comment by Bisola15** [comment]
Hi Jilaga!!! Looovvveeee your design. Well done, I think I saw yours days ago when I just got here and was looking for issues. And I must say, It inspired my creativity by the time I was researching to design mine. Well done! 


Oh and yes, I think this new design up there is a better approach to the last one but the link isn’t present. From my research, social links are links we share to people to direct them to a page. So people should be able to see a link to click on. Which if I'm not wrong you represented on the first two designs.

Again well done!!

**Comment by Ismael-KG** [comment]
This PR is on issue #14

**Comment by jilaga** [comment]
> This PR is on issue #14

>> thanks for linking it @Ismael-KG

**Comment by jilaga** [comment]
> Hi Jilaga!!! Looovvveeee your design. Well done, I think I saw yours days ago when I just got here and was looking for issues. And I must say, It inspired my creativity by the time I was researching to design mine. Well done!
> 
> Oh and yes, I think this new design up there is a better approach to the last one but the link isn’t present. From my research, social links are links we share to people to direct them to a page. So people should be able to see a link to click on. Which if I'm not wrong you represented on the first two designs.
> 
> Again well done!!

> thank you for the feedback.  The social previews are already clickable images so I don't think they really need the links written on the image.

**Comment by Ismael-KG** [comment]
Hi @jilaga – you have some really wonderful content in this PR! Just a couple of thoughts:
* I do love the ["different approach"](https://github.com/open-life-science/branding/pull/12/files#diff-247927de4ccc0209ef47714db27cff3781672233455140f60b31feb4c68680fa) option to the social preview. I would just suggest this be the social preview specifically for, say, the OLS website. The "traditional approach" (with contributors and the star count) might be worth adhering to for the sake of links to the GitHub repository.
* The "different approach" option is great because you made what I think is a great logo! If you built it from scratch, maybe go to issue 27 and share it!
* You've also used this PR to suggest illustrations for values of OLS. This deserves a separate PR that links to issue 38, where we have listed OLS' values. Can you do that? Remove the illustrations from this PR and open a new PR for them. Let me know if this needs clarifying!

**Comment by jilaga** [comment]
> Hi @jilaga – you have some really wonderful content in this PR! Just a couple of thoughts:
> 
> * I do love the ["different approach"](https://github.com/open-life-science/branding/pull/12/files#diff-247927de4ccc0209ef47714db27cff3781672233455140f60b31feb4c68680fa) option to the social preview. I would just suggest this be the social preview specifically for, say, the OLS website. The "traditional approach" (with contributors and the star count) might be worth adhering to for the sake of links to the GitHub repository.
> * The "different approach" option is great because you made what I think is a great logo! If you built it from scratch, maybe go to issue 27 and share it!
> * You've also used this PR to suggest illustrations for values of OLS. This deserves a separate PR that links to issue 38, where we have listed OLS' values. Can you do that? Remove the illustrations from this PR and open a new PR for them. Let me know if this needs clarifying!

I appreciate the thorough feedback @Ismael-KG, I would like to respond accordingly;  

• I designed a few ideas for the social preview image including the 'traditional approach' and they are all here https://github.com/open-life-science/branding/pull/12/commits/33afa0695880a0973a1b796a998c886efc0047ae 

• I didn't necessarily design it from scratch, I just edited an open source vector to suit the design 

• I designed these illustrations https://github.com/jilaga/branding-1/pull/1#issue-1429404060 from scratch and they are solutions I came up with for #45. 
I would admit, I got lost on GitHub trying to make a pr and everything got jumbled up 😭. I would make a new pr and hope I link it to the right issue, Thanks a lot

**Comment by yochannah** [comment]
Jilaga - I'm going to close this, but only because you've done a bunch of beautiful branding work SINCE this PR. Thank you 🙏

**Pull request closed without merging**
