### PR TITLE
New Logo

### PR DESCRIPTION
**Pull request by jilaga**
Uploaded the new logo files to a folder.

### CODE REVIEW

**Comment by bebatut** [comment]
Thanks @jilaga 
Could you put the files in the `logo` folder and move the files of the previous logo into a subfolder `previous-ols-logo`?

**Comment by jilaga** [comment]
Sure! @bebatut. Also, should the Open Seeds Logo files be uploaded to the Logo folder too?

**Comment by jilaga** [comment]
@bebatut for the remaining assets (Business cards, letterheads, social banners/templates, merchandise, stickers and patterns), should I upload them in separate folders?

**Comment by bebatut** [comment]
Yes you can upload them in separated folders like the flyer, but in another Pull Request. Thanks
Can you change the base branch to `master`? Thanks

**Comment by jilaga** [comment]
based to master.

**Review by yochannah — APPROVED** [review]

**Pull request merged**
